### ISSUE TITLE
npm start 报错

### ISSUE THREAD

**Issue by kaen98** [SuperJolly/wxapp-little-shelf#6]
进入 server 目录，使用命令 $ npm install && npm start, 报错！  node.js不太熟悉， 不知道如何解决？

```
kaen@kaen-z7m MINGW64 /d/mini-p/wxapp-little-shelf/server (local)
$ npm start

> server@0.0.0 start D:\mini-p\wxapp-little-shelf\server
> node ./bin/www

D:\mini-p\wxapp-little-shelf\server\app.js:8
const { authorizeMiddleware } = require('./middleware/auth');
      ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (D:\mini-p\wxapp-little-shelf\server\bin\www:7:13)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)

npm ERR! Windows_NT 10.0.17134
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v4.4.3
npm ERR! npm  v2.15.1
npm ERR! code ELIFECYCLE
npm ERR! server@0.0.0 start: `node ./bin/www`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the server@0.0.0 start script 'node ./bin/www'.
npm ERR! This is most likely a problem with the server package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./bin/www
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs server
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls server
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\mini-p\wxapp-little-shelf\server\npm-debug.log
```

**Comment by kaen98** [comment]
已解决!
npm版本低了, 升级npm解决
